version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.41
  - dependency-name: workbox-strategies
    versions:
    - 6.1.0
    - 6.1.5
  - dependency-name: workbox-routing
    versions:
    - 6.1.2
    - 6.1.5
  - dependency-name: workbox-core
    versions:
    - 6.1.2
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.6.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.2
    - 5.1.3
  - dependency-name: workbox-streams
    versions:
    - 6.1.1
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.7
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
  - dependency-name: sass
    versions:
    - 1.32.5
  - dependency-name: sass-loader
    versions:
    - 10.1.1
