AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Template for fetch function

Parameters:
  OriginRequestStackName:
    Type: String
    Description: 'Dev lambda'
    Default: ''
  RecordSetDomainName:
    Type: String
    Description: 'Domain name traffic should be routed to'
  CertificateArn:
    Type: String
  HostedZoneID:
    Type: String
    Description: 'Hosted zone ID domain is part of'
  DeploymentType:
    AllowedValues:
      - 'development'
      - 'production'
    Default: 'development'
    Description: 'Use development or production version'
    Type: String
Conditions:
  UseLambdaTrigger: !Equals
    - !Ref DeploymentType
    - 'development'
Resources:
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt DeployBucket.DomainName
            Id: !Ref DeployBucket
            S3OriginConfig:
              OriginAccessIdentity: ''
        DefaultRootObject: index.html
        Enabled: true
        Aliases:
          - !Ref RecordSetDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: 'sni-only'
        DefaultCacheBehavior:
          MinTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref DeployBucket
          ViewerProtocolPolicy: 'redirect-to-https'
          LambdaFunctionAssociations:
            - !If
              - UseLambdaTrigger
              - EventType: viewer-request
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub ${OriginRequestStackName}-OriginRequestLambdaFunctionVersion
              - !Ref AWS::NoValue
            - !If
              - UseLambdaTrigger
              - EventType: origin-request
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub ${OriginRequestStackName}-OriginRequestLambdaFunctionVersion
              - !Ref AWS::NoValue

  DistributionAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneID
      RecordSets:
        - Name: !Ref RecordSetDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeployBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DeployBucket
                - '/*'
Outputs:
  BucketName:
    Description: The BucketName ID
    Value: !Ref DeployBucket
  Distribution:
    Description: The Distribution ID
    Value: !Ref Distribution
