AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Template for fetch function

Parameters:
  OriginRequestStackName:
    Type: String
    Description: 'Dev lambda'
    Default: ''
  RecordSetDomainName:
    Type: String
    Description: 'Domain name traffic should be routed to'
  RecordSetDomainNameApi:
    Type: String
    Description: 'Domain name traffic should be routed to'
  CertificateArn:
    Type: String
  HostedZoneID:
    Type: String
    Description: 'Hosted zone ID domain is part of'
  DeploymentType:
    AllowedValues:
      - 'development'
      - 'production'
    Default: 'development'
    Description: 'Use development or production version'
    Type: String
Conditions:
  IsDevelopment: !Equals
    - !Ref DeploymentType
    - 'development'
Resources:
  LambdaBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  # Bucket resources for hosting static assets
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DeployBucket
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicRead
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref DeployBucket
                - '/*'
  # CDN resources
  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - Id: !Ref DeployBucket
            DomainName: !Sub '${S3BucketRoot}.s3-website.${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: ''
            CustomOriginConfig:
              HTTPPort: '80'
              HTTPSPort: '443'
              OriginProtocolPolicy: http-only
        DefaultRootObject: index.html
        Enabled: true
        Aliases:
          - !Ref RecordSetDomainName
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: 'sni-only'
        DefaultCacheBehavior:
          MinTTL: 86400
          MaxTTL: 31536000
          ForwardedValues:
            QueryString: true
          TargetOriginId: !Ref DeployBucket
          ViewerProtocolPolicy: 'redirect-to-https'
          Compress: true
          LambdaFunctionAssociations:
            - !If
              - IsDevelopment
              - EventType: viewer-request
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub ${OriginRequestStackName}-OriginRequestLambdaFunctionVersion
              - !Ref AWS::NoValue
            - !If
              - IsDevelopment
              - EventType: origin-request
                LambdaFunctionARN:
                  Fn::ImportValue: !Sub ${OriginRequestStackName}-OriginRequestLambdaFunctionVersion
              - !Ref AWS::NoValue
  DistributionAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneID
      RecordSets:
        - Name: !Ref RecordSetDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt Distribution.DomainName
  ApiGatewayAlias:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneID
      RecordSets:
        - Name: !Ref RecordSetDomainNameApi
          Type: A
          AliasTarget:
            HostedZoneId: !GetAtt ApiGatewayDomainName.DistributionHostedZoneId
            DNSName: !GetAtt ApiGatewayDomainName.DistributionDomainName
  ApiGatewayDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref RecordSetDomainNameApi
      EndpointConfiguration:
        Types:
          - EDGE
Outputs:
  DeployBucket:
    Description: The BucketName ID
    Value: !Ref DeployBucket
  LambdaBucket:
    Description: The BucketName ID
    Value: !Ref LambdaBucket
  Distribution:
    Description: The Distribution ID
    Value: !Ref Distribution
  CertificateArn:
    Description: The Distribution ID
    Value: !Ref CertificateArn
