AWSTemplateFormatVersion: '2010-09-09'
Description: SAM Template for fetch function

# dev distribution order

# prod distribution order

# @TODO https://aws.amazon.com/blogs/networking-and-content-delivery/dynamically-route-viewer-requests-to-any-origin-using-lambdaedge/
Parameters:
  RecordSetDomainName:
    Type: String
    Description: 'Domain name traffic should be routed to'

Resources:
  DeployBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

Outputs:
  BucketName:
    Description: The BucketName ID
    Value: !Ref DeployBucket
